# Generated by Django 5.2.9 on 2026-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('pharmacist', 'Pharmacist')], max_length=10),
        ),
    ]
