# Generated by Django 5.2.9 on 2026-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
