# Generated by Django 5.2.9 on 2026-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_medicalrecord_dispensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
