# Generated by Django 5.2.9 on 2026-02-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_medicalrecord_not_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
