# Generated by Django 5.2.9 on 2026-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_medicalrecord_prescribed_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='created_at',
            new_name='issued_at',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
