# Generated by Django 5.2.9 on 2026-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_rename_created_at_medicalrecord_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacist_id',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='phone',
            field=models.CharField(default='TEMP', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='qualification',
            field=models.CharField(default='TEMP', max_length=100),
            preserve_default=False,
        ),
    ]
