# Generated by Django 5.2.9 on 2026-02-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_pharmacist_pharmacist_id_pharmacist_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
