# Generated by Django 5.2.9 on 2026-02-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_rename_department_student_course_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(default='TEMP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='TEMP', max_length=100),
            preserve_default=False,
        ),
    ]
