# Generated by Django 5.2.9 on 2026-02-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_doctor_address_doctor_allergies_doctor_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.pharmacist'),
        ),
    ]
