# Generated by Django 5.2.9 on 2026-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_medicalrecord_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='student_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
